export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const UPDATE_ORDER_LIST = "UPDATE_ORDER_LIST";

export const UPDATE_REVIEWS = "UPDATE_REVIEWS";

export const UPDATE_FAVOURITES = "UPDATE_FAVOURITES";

export const UPDATE_CARTS = "UPDATE_CARTS";
